#!/bin/bash

source ~/.config/dtf-config/config
rofi_theme=${rofi_theme:-black}

if [[ $rofi_theme == "white" ]]; then
	path_to_theme="~/.config/rofi/rofi_theme/white/white.rasi"
else
	path_to_theme="~/.config/rofi/rofi_theme/black/black.rasi"
fi

main_menu_height=220px
main_menu_width=300px

apps_kbdn="󰀻  Apps Keybinds"
sys_kbdn="  System Keybinds"
quit="Exit 󰈆 "

select=$(echo -e "$sys_kbdn\n$apps_kbdn\n$quit" | rofi -dmenu -i -p '   Keybinds ' -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {width: $main_menu_width; height: $main_menu_height;}" -theme $path_to_theme)

case $select in
	$apps_kbdn)
		~/.config/rofi/modules/rofi-i3-keybinds/rofi-i3-keybinds-apps.sh
		;;
	$sys_kbdn)
		~/.config/rofi/modules/rofi-i3-keybinds/rofi-i3-keybinds-system.sh
		;;
esac
