#!/usr/bin/env bash

#THIS SCRIPT WAS FABRICATED BY ME (Xgameisdabest, aka xytozine)

source ~/.config/dtf-config/config
rofi_theme=${rofi_theme:-black}

if [[ $rofi_theme == "white" ]]; then
	path_to_theme="~/.config/rofi/rofi_theme/white/white.rasi"
else
	path_to_theme="~/.config/rofi/rofi_theme/black/black.rasi"
fi

I3_SETTINGS_PATH=~/.config/i3/scripts/i3-settings/

source $I3_SETTINGS_PATH/dunst_section
source $I3_SETTINGS_PATH/i3_section
source $I3_SETTINGS_PATH/picom_section
source $I3_SETTINGS_PATH/polybar_section
source $I3_SETTINGS_PATH/rofi_section

### MAIN MENU

main_menu_height=555px
main_menu_width=295px

goback="Back 󰌍 "
quit="Exit 󰈆 "

i3config="󰨇  i3 Desktop  "
polybar="  Polybar  "
btrlockscreen="󰷛  Lock Screen"
picomconfig="󰢹  Picom  "
arandr="󰨤  Resolution"
wallpaper="  Wallpaper"
gestures="󱠡  Gestures"
rofi="󰮫  Rofi  "
zshconfig="  Zsh"
dunst="󰵙  Notification "
main_menu(){
	select=$(echo -e "$i3config\n$rofi\n$polybar\n$picomconfig\n$dunst\n$zshconfig\n$btrlockscreen\n$gestures\n$wallpaper\n$arandr\n$goback\n$quit"  | rofi -dmenu -i -theme-str "window {height: $main_menu_height; width: $main_menu_width;}" -theme-str "listview {columns: 1; layout: vertical;}" -p " Settings   " -theme $path_to_theme)

	case $select in
		$i3config)
			i3_submenu
			;;
		$picomconfig)
			picom_submenu
			;;
		$arandr)
			arandr
			;;
		$wallpaper)
			waypaper
			;;
		$gestures)
			$TERMINAL -e nvim ~/.config/libinput-gestures.conf
			;;
		$rofi)
			rofi_submenu
			;;
		$btrlockscreen)
			$TERMINAL -e nvim ~/.config/betterlockscreen/betterlockscreenrc
			;;
		$polybar)
			polybar_submenu
			;;
		$zshconfig)
			$TERMINAL -e nvim ~/.zshrc
			;;
		$dunst)
			dunst_submenu
			;;
		$goback)
			~/.config/rofi/modules/rofi-user-settings
			;;
		$quit)
			echo "exit"
			exit 0
			;;
	esac
}

### PROGRAM MAIN EXEC

main_menu
