#!/bin/bash
### DUNST SUBMENU

i3_setting_submenu_height=405px
i3_setting_submenu_width=285px

i3_setting_submenu(){
	main_config="󰅍  Main File"
	i3_section="󰅍  i3"
	dunst_section="󰅍  Notification"
	picom_section="󰅍  Picom"
	rofi_section="󰅍  Rofi"
	polybar_section="󰅍  Polybar"
	i3_settings_section="󰅍  This Menu"

	select10=$(echo -e "$main_config\n$i3_settings_section\n$i3_section\n$dunst_section\n$picom_section\n$rofi_section\n$polybar_section\n$goback" | rofi -dmenu -i -theme-str "window {height: $i3_setting_submenu_height; width: $i3_setting_submenu_width;}" -theme-str "listview {columns: 1; layout: vertical;}" -p " Menu Config   ")

	case $select10 in
		$i3_section)
			$TERMINAL -e nvim ~/.config/rofi/modules/i3-settings/i3_section
			;;
		$i3_settings_section)
			$TERMINAL -e nvim ~/.config/rofi/modules/i3-settings/i3-settings_section
			;;
		$dunst_section)
			$TERMINAL -e nvim ~/.config/rofi/modules/i3-settings/dunst_section
			;;
		$picom_section)
			$TERMINAL -e nvim ~/.config/rofi/modules/i3-settings/picom_section
			;;
		$rofi_section)
			$TERMINAL -e nvim ~/.config/rofi/modules/i3-settings/rofi_section
			;;
		$main_config)
			$TERMINAL -e nvim ~/.config/rofi/modules/i3-settings/rofi-i3-settings
			;;
		$polybar_section)
			$TERMINAL -e nvim ~/.config/rofi/modules/i3-settings/polybar_section
			;;
		$goback)
			rofi_submenu
			;;
	esac
}
