#!/bin/bash
### PICOM SUBMENU

picom_submenu_height=255px
picom_submenu_width=465px

picom_submenu(){
	trans_when_unfocused="󰢹  Transparent When Unfocused"
	not_trans_when_unfocused="󰢹  Not Transparent When Unfocused"
	picom_start="󱓞  Compositor Launch"
	
	select5=$(echo -e "$trans_when_unfocused\n$not_trans_when_unfocused\n$picom_start\n$goback" | rofi -dmenu -i -theme-str "window {height: $picom_submenu_height; width: $picom_submenu_width;}" -theme-str "listview {columns: 1; layout: vertical;}" -p " Picom   ")

	case $select5 in
		$trans_when_unfocused)
			$TERMINAL -e nvim ~/.config/picom/picom_trans_unfocus.conf
			;;
		$not_trans_when_unfocused)
			$TERMINAL -e nvim ~/.config/picom/picom_no_trans_unfocus.conf
			;;
		$picom_start)
			$TERMINAL -e nvim ~/.config/picom/picom_launch.sh
			;;
		$goback)
			main_menu
			;;
	esac
}
