#!/usr/bin/env bash

#COULD NOT FIND THE ORIGINAL AUTHOR
#THIS SCRIPT WAS MODIFIED BY ME (Xgameisdabest, aka xytozine)

main_menu(){

source ~/.config/dtf-config/config

#when add new entry make sure to add 35 to height
main_menu_height=430px
main_menu_width=270px
notification_timeout=1100

polybar_top=${polybar_top:-false}
rofi_theme=${rofi_theme:-black}

if [[ $polybar_top == "true" ]]; then
	location="north east"

	main_menu_x_offset=-150px
	main_menu_y_offset=70px
else
	location="south east"
				 
	main_menu_x_offset=-150px
	main_menu_y_offset=-70px
fi

if [[ $rofi_theme == "white" ]]; then
	path_to_theme="~/.config/rofi/rofi_theme/white/white.rasi"
else
	path_to_theme="~/.config/rofi/rofi_theme/black/black.rasi"
fi

#main
time_left=$(acpi | grep -oP '\d{2}:\d{2}:\d{2}(?= remaining)')
charged_left=$(acpi | grep -oP '\d{2}:\d{2}:\d{2}(?= until charged)')
status="$(acpi | sed 's/Not charging/Charging/g' | grep 'Battery 0' | awk '{print $3}' | sed 's/,//g')"
bat_percentage="$(acpi | sed 's/Not charging//g' | grep 'Battery 0' | awk '{print $4}' | sed 's/,//g')"
#bat_percentage_number="$(acpi | sed 's/Not charging//g' | grep 'Battery 0' | awk '{print $4}' | sed 's/,//g' | sed 's/%//g')"
power_mode_status="$(powerprofilesctl get)"

set_mode_performace() {
	powerprofilesctl set performance
	light -S 100
	notify-send -t $notification_timeout -h string:x-dunst-stack-tag:power_mode_status "Power set to performance mode 󰓅"
	~/.config/dunst/scripts/volume.sh brightness_status
}

set_mode_balanced() {
	powerprofilesctl set balanced
	light -S 79
	notify-send -t $notification_timeout -h string:x-dunst-stack-tag:power_mode_status "Power set to balance mode 󰾅"
	~/.config/dunst/scripts/volume.sh brightness_status
}

set_mode_power_saver() {
	powerprofilesctl set power-saver
	light -S 61
	notify-send -t $notification_timeout -h string:x-dunst-stack-tag:power_mode_status "Power set to power-saver mode 󰾆"
	~/.config/dunst/scripts/volume.sh brightness_status
}

rofi_cmd() {
	if [[ $status == "Discharging" ]]; then
		rofi -dmenu -i -theme $path_to_theme -theme-str "window {height: $main_menu_height; width: $main_menu_width; location: $location; x-offset: $main_menu_x_offset; y-offset: $main_menu_y_offset;}" -theme-str "listview {columns: 1; layout: vertical;}" -selected-row 2 -mesg "$(echo -e " MODE: $power_mode_status\n TIME: $time_left")" -p " $bat_percentage 󰁹 "
	elif [[ $status == "Charging" ]]; then
		rofi -dmenu -i -theme $path_to_theme -theme-str "window {height: $main_menu_height; width: $main_menu_width; location: $location; x-offset: $main_menu_x_offset; y-offset: $main_menu_y_offset;}" -theme-str "listview {columns: 1; layout: vertical;}" -selected-row 2 -mesg "$(echo -e " MODE: $power_mode_status\n FULL: $charged_left")" -p " $bat_percentage 󰂅 "
	elif [[ $status == "Full" ]]; then
		rofi -dmenu -i -theme $path_to_theme -theme-str "window {height: $main_menu_height; width: $main_menu_width; location: $location; x-offset: $main_menu_x_offset; y-offset: $main_menu_y_offset;}" -theme-str "listview {columns: 1; layout: vertical;}" -selected-row 2 -mesg "$(echo -e " MODE: $power_mode_status")" -p " Full 󱐋 "
	fi
}

# Options
quit="Exit 󰈆 "
performance='󰓅  Performance'
medium='󰾅  Balanced'
power='󰾆  Power Saver'
power_manager="󰖯  Power Manager"
auto_cpufreq="󰖯  auto-cpufreq"

run_rofi() {
	echo -e "$power_manager\n$auto_cpufreq\n$performance\n$medium\n$power\n$quit" | rofi_cmd
}

# Execute Command

run_cmd() {
		if [[ $1 == '--performance' ]]; then
			set_mode_performace
		elif [[ $1 == '--medium' ]]; then
			set_mode_balanced
		elif [[ $1 == '--power' ]]; then
			set_mode_power_saver
		fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
	"")
	    exit
	;;
    $quit)
	    exit
	;;
    $performance)
		run_cmd --performance
		main_menu
        ;;
    $medium)
		run_cmd --medium
		main_menu
        ;;
    $power)
		run_cmd --power
		main_menu
        ;;
    $power_manager)
		xfce4-power-manager-settings
	;;
    $auto_cpufreq)
		auto-cpufreq-gtk
	;;
esac
}
main_menu
