#!/usr/bin/env bash

#THIS SCRIPT WAS FABRICATED BY ME (Xgameisdabest, aka xytozine)

source ~/.config/dtf-config/config
rofi_theme=${rofi_theme:-black}

if [[ $rofi_theme == "white" ]]; then
	path_to_theme="~/.config/rofi/rofi_theme/white/white.rasi"
else
	path_to_theme="~/.config/rofi/rofi_theme/black/black.rasi"
fi

web="  Web Search"
yt="  Youtube"
github="  Github"
nerdfonts="󰌧  Nerd Fonts"
this_dotfiles="󰌧  This Dotfiles"
quit="Exit 󰈆 "

web(){
search=$( echo | rofi -dmenu -theme $path_to_theme -theme-str "window {height: 90px;}" -p " Search   " )
search_engine="https://search.brave.com/search?q="
main() {
    if [[ -n "$search" ]]; then
      url="$search_engine$search"
      xdg-open "$url"
    else
		exit
	      fi
}
main
exit 0
}

yt(){
search=$( echo | rofi -dmenu -theme $path_to_theme -theme-str "window {height: 90px;}" -p " Videos   " )
search_engine="https://www.youtube.com/results?search_query="
main() {
    if [[ -n "$search" ]]; then
      url="$search_engine$search"
      xdg-open "$url"
    else
		exit
	      fi
}
main
exit 0
}

github(){
search=$( echo | rofi -dmenu -theme $path_to_theme -theme-str "window {height: 90px;}" -p " User/Project   " )
search_engine="https://github.com/"
main() {
    if [[ -n "$search" ]]; then
      url="$search_engine$search"
      xdg-open "$url"
    else
		exit
	      fi
}
main
exit 0
}

dotfiles(){
xdg-open https://github.com/xgameisdabest/dotfiles
exit 0
}

nerdfonts_func(){
xdg-open https://www.nerdfonts.com/cheat-sheet
exit 0
}

select=$( echo -e "$web\n$yt\n$github\n$nerdfonts\n$this_dotfiles\n$quit" | rofi -dmenu -theme $path_to_theme -theme-str "window {height: 330px; width: 280px;}" -theme-str "listview {columns: 1; layout: vertical;}" -p " Select Search Mode ")

case $select in
	$web)
		web
		;;
	$yt)
		yt
		;;
	$github)
		github
		;;
	$this_dotfiles)
		dotfiles
		;;
	$nerdfonts)
		nerdfonts_func
		;;
esac
