#!/bin/bash

list_history="$(dunstctl history | jq -r '
    .data[0][] |
    select(
	(.summary.data | contains("Dotfiles Update  ") | not) and
	(.summary.data | contains("Wifi Enabled") | not) and
	(.summary.data | contains("Wifi Disabled") | not) and
	(.summary.data | contains("󰗨 Removed Network") | not) and
	(.summary.data | contains("󰗨 Removing Network") | not) and
	(.summary.data | contains("Getting list of available Wi-Fi networks") | not) and
	(.summary.data | contains("Scanning Nearby Devices") | not) and
	(.summary.data | contains("Attempting to connect to") | not) and
	(.summary.data | contains("Airplane Mode: Active") | not) and
	(.summary.data | contains("Airplane Mode: Inactive") | not) and
	(.summary.data | contains("Battery Time Remaining: ") | not) and
	(.summary.data | contains("Charge Time Remaining: ") | not) and
	(.summary.data | contains("Battery Full") | not) and
	(.summary.data | contains("Power set to performance mode") | not) and
	(.summary.data | contains("Power set to balance mode") | not) and
	(.summary.data | contains("Power set to power-saver mode") | not) and
	(.summary.data | contains("CONNECTING TO PHONE") | not) and
	(.summary.data | contains("Screenshotted") | not) and
	(.summary.data | contains("Window Screenshotted") | not) and
	(.summary.data | contains("Selected Area Screenshotted") | not) and
        (.summary.data | contains("RESIZE MODE. PRESS esc TO EXIT!") | not) and
	(.summary.data | contains("Window stacking enabled 󰖲") | not) and
	(.summary.data | contains("Window tab stacking enabled 󰖲") | not) and
	(.summary.data | contains("Window split enabled 󰟘") | not) and
	(.summary.data | contains("") | not) and
        (.summary.data | contains("") | not) and
	(.summary.data | contains("") | not) and
        (.summary.data | contains("") | not) and
	(.summary.data | contains("") | not) and
	(.summary.data | contains("Charging 󰂅") | not) and
	(.summary.data | contains("Discharging 󰁹") | not) and
	(.summary.data | contains("") | not) and
	(.summary.data | contains("") | not) and
	(.summary.data | contains("󰖩") | not) and
	(.summary.data | contains("") | not) and
	(.summary.data | contains("") | not)) |
    "\(.summary.data)"
')"

if [[ $list_history != "" ]]; then
	echo " 󱅫  "
else
	echo " 󰂜  "
fi
