#!/usr/bin/env bash

# CMDs
uptime="`uptime -p | sed -e 's/up //g'`"
host=`hostname`

# Options
shutdown='  Shut Down'
#shutdown=' '
reboot='  Reboot'
#reboot=' '
lock='  Lock'
#lock=' '
suspend='󰤄  Suspend'
#suspend='󰤄 '
#logout='󰍃  -> Get the fuck out'
logout='󰍃  Log out'
#logout='󰍃 '
yes='✔'
no='✗'

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-i \
		-theme-str 'window {height: 385; width: 350px;}' \
		-p " Select   " \
		-mesg "Uptime: $uptime" }
}

# Confirmation CMD
confirm_cmd() {
	rofi -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 350px;}' \
		-theme-str 'listview {columns: 2; lines: 1;}' \
		-theme-str 'element-text {horizontal-align: 0.5;}' \
		-theme-str 'textbox {horizontal-align: 0.5;}' \
		-dmenu \
		-p 'Confirmation' \
		-mesg 'Are you Sure?'
}

# Ask for confirmation
confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$lock\n$suspend\n$logout\n$reboot\n$shutdown" | rofi_cmd
}

# Execute Command
run_cmd() {
	selected="$yes"
	if [[ "$selected" == "$yes" ]]; then
		if [[ $1 == '--shutdown' ]]; then
			poweroff
		elif [[ $1 == '--reboot' ]]; then
			reboot
		elif [[ $1 == '--suspend' ]]; then
			mpc -q pause
			amixer set Master mute
			systemctl suspend
			betterlockscreen -l
		elif [[ $1 == '--logout' ]]; then
			i3-msg 'exit'
		fi
	else
		exit 0
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $shutdown)
		run_cmd --shutdown
        ;;
    $reboot)
		run_cmd --reboot
        ;;
    $lock)
		betterlockscreen -l
        ;;
    $suspend)
		run_cmd --suspend
        ;;
    $logout)
		run_cmd --logout
        ;;
esac

