#!/usr/bin/env bash

status=$(acpi | grep 'Battery 0'|awk '{print $3}' | sed 's/,//g')

if [[ $status == "Discharging" ]]; then
	notify-send "Battery Time Remaining: $(acpi -b | grep -oP '\d{1,2}:\d{2}:\d{2}')" "CURRENT PROFILE: $(powerprofilesctl get)"
elif [[ $status == "Charging" ]]; then
	notify-send "Charge Time Remaining: $(acpi -b | grep -oP '\d{1,2}:\d{2}:\d{2}')" "CURRENT PROFILE: $(powerprofilesctl get)"
elif [[ $status == "Full" ]]; then
	notify-send "Battery Full" "CURRENT PROFILE: $(powerprofilesctl get)"
fi

# Options
performance='󰓅  Performance'
medium='󰾅  Balance'
power='󰾆  Power Saver'
power_manager="󰖯  Power Manager"

bat_percentage=$(upower -i $(upower -e | grep 'BAT') | grep -E "percentage" | sed 's/percentage//g' | sed 's/://g' | sed 's/  //g')

rofi_cmd() {
	if [[ $status == "Discharging" ]]; then
		rofi -dmenu -i -theme-str 'window {height: 255px; width: 270px;}' -p " $bat_percentage 󰁹 "  -theme-str "listview {columns: 1; layout: vertical;}" -selected-row 1
	elif [[ $status == "Charging" ]]; then
		rofi -dmenu -i -theme-str 'window {height: 255px; width: 270px;}' -p " $bat_percentage 󱐋 "  -theme-str "listview {columns: 1; layout: vertical;}" -selected-row 1
	elif [[ $status == "Full" ]]; then
		rofi -dmenu -i -theme-str 'window {height: 255px; width: 270px;}' -p " Full 󰂄 "  -theme-str "listview {columns: 1; layout: vertical;}" -selected-row 1
	fi
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$power_manager\n$performance\n$medium\n$power" | rofi_cmd
}

# Execute Command
run_cmd() {
		if [[ $1 == '--performance' ]]; then
			powerprofilesctl set performance
			notify-send "Power set to performance mode 󰓅"
		elif [[ $1 == '--medium' ]]; then
			powerprofilesctl set balanced
			notify-send "Power set to balance mode 󰾅"
		elif [[ $1 == '--power' ]]; then
			powerprofilesctl set power-saver
			notify-send "Power set to power-saver mode 󰾆"
		fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
	"")
		exit
	;;
    $performance)
		run_cmd --performance
        ;;
    $medium)
		run_cmd --medium
        ;;
    $power)
		run_cmd --power
        ;;
	$power_manager)
		xfce4-power-manager-settings
	;;
esac
