#!/bin/bash

source ~/.config/dtf-config/config
rofi_theme=${rofi_theme:-black}
if [[ $rofi_theme == "white" ]]; then
	path_to_theme="~/.config/rofi/rofi_theme/white/white.rasi"
else
	path_to_theme="~/.config/rofi/rofi_theme/black/black.rasi"
fi

main_menu_height=225px
main_menu_width=220px

mode_menu_height=500px
mode_menu_width=375px

goback="Back 󰌍 "
quit="Exit 󰈆 "

#Monitor pick
main_menu(){
monitor_list=$(wlr-randr | awk '/^[A-Za-z0-9-]+ / {print $1}')

monitor_picked=$( echo -e "$monitor_list\n$quit" | rofi -dmenu -p " Monitors 󰍺  " -theme $path_to_theme -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {width: $main_menu_width; height: $main_menu_height;}")

if [[ -z "$monitor_picked" ]] || [[ "$monitor_picked" = "$quit" ]]; then
	exit
else
	mode_menu
fi
}

mode_menu(){
#List all available resolutions+rates for chosen monitor
mode=$(wlr-randr | awk -v mon="$monitor_picked" '
    $1 == mon {inside=1; next}
    /^[A-Za-z0-9-]+ / {inside=0}
    inside && /^[ ]+[0-9]+x[0-9]+/ {
        res=$1
        gsub(/[^0-9.]/,"",$2) # sometimes refresh is in $2, sometimes $3
        gsub(/[^0-9.]/,"",$3)
        rate = ($3 != "" ? $3 : $2)
        print res "@" rate
    }
')

#Getting user input
mode_picked=$(echo -e "$mode\n$goback" | rofi -dmenu -p " Resolution 󰹑  " -theme $path_to_theme -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {width: $mode_menu_width; height: $mode_menu_height;}")

if [[ -z "$mode_picked" ]]; then
	exit
elif [[ $mode_picked == "$goback" ]]; then
	main_menu
fi

#Apply the selection
res=$(echo "$mode_picked" | cut -d'@' -f1)
rate=$(echo "$mode_picked" | cut -d'@' -f2)

#echo $monitor_picked,$res@$rate
hyprctl keyword monitor "$monitor_picked,$res@$rate,auto,1"
}

main_menu
