#!/usr/bin/env bash

# URLS=(
#   ["Google"]="https://www.google.com/search?q="
#   ["Bing"]="https://www.bing.com/search?q="
#   ["Yahoo"]="https://search.yahoo.com/search?p="
#   ["Duckduckgo"]="https://www.duckduckgo.com/?q="
#   ["Yandex"]="https://yandex.ru/yandsearch?text="
#   ["Youtube"]="https://www.youtube.com/results?search_query="
# )

web="  Web Search"
yt="  Youtube"
github="  Github"
this_dotfiles="󰌧  This Dotfile"

web(){
search=$( echo | rofi -dmenu -i -theme-str "window {height: 90px;}" -p " Search   " )
search_engine="https://www.google.com/search?q="
main() {
    if [[ -n "$search" ]]; then
      url="$search_engine$search"
      xdg-open "$url"
    else
		exit
	      fi
}
main
exit 0
}

yt(){
search=$( echo | rofi -dmenu -theme-str "window {height: 90px;}" -p " Videos   " )
search_engine="https://www.youtube.com/results?search_query="
main() {
    if [[ -n "$search" ]]; then
      url="$search_engine$search"
      xdg-open "$url"
    else
		exit
	      fi
}
main
exit 0
}

github(){
search=$( echo | rofi -dmenu -theme-str "window {height: 90px;}" -p " User/Project   " )
search_engine="https://github.com/"
main() {
    if [[ -n "$search" ]]; then
      url="$search_engine$search"
      xdg-open "$url"
    else
		exit
	      fi
}
main
exit 0
}

dotfiles(){
xdg-open https://github.com/xgameisdabest/my-i3-config-dotfiles
exit 0
}

select=$( echo -e "$web\n$yt\n$github\n$this_dotfiles" | rofi -dmenu -theme-str "window {height: 260px; width: 280px;}" -theme-str "listview {columns: 1; layout: vertical;}" -p " Select Search Mode ")

case $select in
	$web)
		web
		;;
	$yt)
		yt
		;;
	$github)
		github
		;;
	$this_dotfiles)
		dotfiles
		;;
esac
