#!/usr/bin/env bash

# Options
performance='Performance 󰓅 '
medium='Balance 󰾅 '
power='Power Saver 󰾆 '
power_manager="Power Manager 󰖯 "

rofi_cmd() {
	rofi -dmenu -theme-str 'window {height: 255px; width: 255px;}' -p "Mode:"  -theme-str "listview {columns: 1; layout: vertical;}" -selected-row 1
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$power_manager\n$performance\n$medium\n$power" | rofi_cmd
}

# Execute Command
run_cmd() {
		if [[ $1 == '--performance' ]]; then
			powerprofilesctl set performance
			notify-send "Power set to performance mode 󰓅"
		elif [[ $1 == '--medium' ]]; then
			powerprofilesctl set balanced
			notify-send "Power set to balance mode 󰾅"
		elif [[ $1 == '--power' ]]; then
			powerprofilesctl set power-saver
			notify-send "Power set to power-saver mode 󰾆"
		fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
	"")
		exit
	;;
    $performance)
		run_cmd --performance
        ;;
    $medium)
		run_cmd --medium
        ;;
    $power)
		run_cmd --power
        ;;
	$power_manager)
		xfce4-power-manager-settings
	;;
esac
