#!/usr/bin/env bash

#THIS SCRIPT WAS FABRICATED BY ME (Xgameisdabest, aka xytozine)

source ~/.config/dtf-config/config
rofi_theme=${rofi_theme:-black}

if [[ $rofi_theme == "white" ]]; then
	path_to_theme="~/.config/rofi/rofi_theme/white/white.rasi"
else
	path_to_theme="~/.config/rofi/rofi_theme/black/black.rasi"
fi

web="  Web Search (Brave)  "
yt="  Youtube  "
github="  Github  "
ai="  Ai  "
virustotal="󰨯  Virus Total 󰌧 "
flathub="  Flathub 󰌧 "
nerdfonts="󰛖  Nerd Fonts 󰌧 "
this_dotfiles="  This Dotfiles Repo 󰌧 "
back="Back 󰌍"
quit="Exit 󰈆 "

web() {
	search=$(echo | rofi -x11 -dmenu -theme $path_to_theme -theme-str "window {height: 90px;}" -p " Search   ")
	search_engine="https://search.brave.com/search?q="
	main() {
		if [[ -n "$search" ]]; then
			url="$search_engine$search"
			xdg-open "$url" &
			exit 0
		else
			exit 0
		fi
	}
	main
	exit 0
}

yt() {
	open_the_webpage_yt="󰖟  Open the website 󰌧 "
	open_the_search_bar_yt="  Search for videos"

	choice=$(echo -e "$open_the_webpage_yt\n$open_the_search_bar_yt\n$back" | rofi -x11 -dmenu -theme $path_to_theme -theme-str "window {height: 210px; width: 330px;}" -p " Videos   ")

	search_yt() {
		search=$(echo | rofi -x11 -dmenu -theme $path_to_theme -theme-str "window {height: 90px;}" -p " Videos   ")
		search_engine="https://www.youtube.com/results?search_query="
		main() {
			if [[ -n "$search" ]]; then
				url="$search_engine$search"
				xdg-open "$url" &
				exit 0
			else
				exit 0
			fi
		}
		main
		exit 0
	}

	case $choice in
	$open_the_webpage_yt)
		xdg-open https://youtube.com &
		exit 0
		;;
	$open_the_search_bar_yt)
		search_yt
		;;
	$back)
		main
		;;
	esac
}

github() {
	open_the_webpage_git="󰖟  Open the website 󰌧 "
	open_the_search_bar_git="  Search for repositories"

	choice=$(echo -e "$open_the_webpage_git\n$open_the_search_bar_git\n$back" | rofi -x11 -dmenu -theme $path_to_theme -theme-str "window {height: 210px; width: 380px;}" -p " Github   ")

	search_github() {
		search=$(echo | rofi -x11 -dmenu -theme $path_to_theme -theme-str "window {height: 90px;}" -p " Repositories   ")
		search_engine="https://github.com/search?q="
		main() {
			if [[ -n "$search" ]]; then
				query=$(echo "$search" | sed 's/ /+/g')
				url="${search_engine}${query}&type=repositories"
				xdg-open "$url" &
				exit 0
			else
				exit 0
			fi
		}
		main
		exit 0
	}

	case $choice in
	$open_the_webpage_git)
		xdg-open https://github.com &
		exit 0
		;;
	$open_the_search_bar_git)
		search_github
		;;
	$back)
		main
		;;
	esac

}

ai() {
	gemini="  Gemini 󰌧 "
	chatgpt="  ChatGpt 󰌧 "
	claude="  Claude 󰌧 "
	model_choice=$(echo -e "$gemini\n$chatgpt\n$claude\n$back" | rofi -x11 -dmenu -theme $path_to_theme -theme-str "window {height: 245px; width: 280px;}" -theme-str "listview {columns: 1; layout: vertical;}" -p " Ai  ")

	case $model_choice in
	$gemini)
		xdg-open https://gemini.google.com &
		exit 0
		;;
	$chatgpt)
		xdg-open https://chatgpt.com &
		exit 0
		;;
	$claude)
		xdg-open https://claude.ai &
		exit 0
		;;
	$back)
		main
		;;
	esac
}

main() {
	select=$(echo -e "$web\n$yt\n$ai\n$github\n$flathub\n$virustotal\n$nerdfonts\n$this_dotfiles\n$quit" | rofi -x11 -dmenu -theme $path_to_theme -theme-str "window {height: 435px; width: 350px;}" -theme-str "listview {columns: 1; layout: vertical;}" -p " Web Shortcut & Search  ")

	case $select in
	$web)
		web
		;;
	$yt)
		yt
		;;
	$github)
		github
		;;
	$this_dotfiles)
		xdg-open https://github.com/xgameisdabest/dotfiles &
		exit 0
		;;
	$nerdfonts)
		xdg-open https://www.nerdfonts.com/cheat-sheet &
		exit 0
		;;
	$virustotal)
		xdg-open https://www.virustotal.com &
		exit 0
		;;
	$ai)
		ai
		;;
	$flathub)
		xdg-open https://flathub.org &
		exit 0
		;;
	esac
}

main
