#!/usr/bin/env bash

#COULD NOT FIND THE ORIGINAL AUTHOR
#THIS SCRIPT WAS MODIFIED BY ME (Xgameisdabest, aka xytozine)

source ~/.config/dtf-config/config

main_menu_height=420px
main_menu_width=350px

bar_top=${bar_top:-false}
rofi_theme=${rofi_theme:-black}

if [[ $bar_top == "true" ]]; then
	location="north east"

	main_menu_x_offset=-10px
	main_menu_y_offset=70px
else
	location="south east"

	main_menu_x_offset=-10px
	main_menu_y_offset=-70px
fi

if [[ $rofi_theme == "white" ]]; then
	path_to_theme="~/.config/rofi/rofi_theme/white/white.rasi"
else
	path_to_theme="~/.config/rofi/rofi_theme/black/black.rasi"
fi

# uptime and hosts
uptime=$(uptime -p | sed -e "s/up //g")
user=$(whoami)
host=$(hostname)

# Options
shutdown='  Power off'
reboot='  Reboot'
lock='  Lock'
suspend='󰤄  Suspend'
logout='󰍃  Log out'

chosen=$(echo -e "$lock\n$suspend\n$logout\n$reboot\n$shutdown" | rofi -dmenu -i -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {height: $main_menu_height; width: $main_menu_width; location: $location; x-offset: $main_menu_x_offset; y-offset: $main_menu_y_offset;}" -theme $path_to_theme -p " Select   " -mesg "$(echo -e " Uptime: $uptime\n Host: $host\n User: $user")")

case $chosen in
    $shutdown)
	poweroff
        ;;
    $reboot)
	reboot
        ;;
    $lock)
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		~/.config/hypr/scripts/hyprlock_current_bg.sh
	else
		betterlockscreen -l
	fi
        ;;
    $suspend)
	mpc -q pause
	amixer set Master mute
	systemctl suspend
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		hyprlock
	else
		betterlockscreen -l
	fi
        ;;
    $logout)
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		killall -SIGINT waybar
		killall usb-watch.sh
		killall udevadm
		hyprctl dispatch exit
	else
		i3-msg 'exit'
	fi
        ;;
esac
